// <auto-generated />
using System;
using BeerOverflow.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeerOverflow.Database.Migrations
{
    [DbContext(typeof(BeerOverflowDbContext))]
    [Migration("20201010113027_AddRating")]
    partial class AddRating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeerOverflow.Models.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ABV")
                        .HasColumnType("real");

                    b.Property<Guid>("BreweryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBeerOfTheMonth")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnlisted")
                        .HasColumnType("bit");

                    b.Property<int>("Mililiters")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("StyleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.HasIndex("StyleId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("133e0d92-cedc-40a7-b8fd-e5669611b3dc"),
                            ABV = 6.7f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clear medium yellow colour with a large, frothy, good lacing, mostly lasting, white head. Aroma is moderate malty, pale malt, moderate hoppy, flowers, citrus, light passion fruit. Flavor is moderate sweet and bitter with a long duration, passion fruit, fruity hops, citrus, fruity, pale malt. Body is medium, texture is oily to watery, carbonation is soft.",
                            ImageURL = "https://birka.bg/wp-content/uploads/2018/10/baso.jpg",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 0,
                            Name = "Basi Kefa",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        },
                        new
                        {
                            Id = new Guid("e13fe243-c8b3-494d-acca-39ea27cd8d41"),
                            ABV = 6f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pours cloudy with a brief frothy head, plenty of lacing but no bead. Mid amber/ dirty orange in colour. Aromas of orange, banana and cereal. Very smooth in the mouth with flavours of banana, orange and pineapple over a base of honeyed cereal. Quite bitter in the finish, but scarcely any sweetness. Overall, another very enjoyable and well made Bulgarian IPA that is actually from Greece.",
                            ImageURL = "https://cdn.dribbble.com/users/1621762/screenshots/4008898/dribble.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 330,
                            Name = "Ailyak Cryo Mosaic",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        },
                        new
                        {
                            Id = new Guid("bacfedee-043c-4c26-b135-76cb2a092f1d"),
                            ABV = 5.5f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complex IPA, with rich aroma of citrus, pine, red fruit",
                            ImageURL = "https://birka.bg/wp-content/uploads/2018/08/%D0%BE%D0%BF%D0%B0%D1%81%D0%B5%D0%BD.jpg",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 0,
                            Name = "Opasen Char",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        },
                        new
                        {
                            Id = new Guid("631a4aff-5de7-4609-b7e1-6d8ba402adcc"),
                            ABV = 5.3f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Slightly cloudy, faint amber colour with average, frothy, slowoly osteoporosing, minimally lacing, white head. Caramel malty and citrusy, slightly leafy, hoppy aroma, hints of lemon tea, cautious doughy yeasty overtones. Taste is slightly dry, citrusy, minimally leafy, hoppy, minimally sweet caramel malty basis, hints of lemon tea, instant lemon tea, cautious smoky overtones; slightly overcarbonated.",
                            ImageURL = "https://birka.bg/wp-content/uploads/2018/10/po.jpg",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 0,
                            Name = "Po Poleka",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        },
                        new
                        {
                            Id = new Guid("b9c4fd4c-dd66-4418-add3-4e8199913413"),
                            ABV = 5.5f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unclear red, small foamy head. Rose hip, hibiscus lemon, tart notes, ice tea, grenadine, red currant Dry sourness. Medium bodied, oily watery texture, lively carbonated, tart dry sour finish. Lovely tasty beer.",
                            ImageURL = "https://birka.bg/wp-content/uploads/2019/08/dirty.jpg",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 0,
                            Name = "Freigeist Dirty Flamingo",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        },
                        new
                        {
                            Id = new Guid("4d65361e-c387-463c-b7ba-deff805032e5"),
                            ABV = 4.6f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Pours clear deep gold, almost pale amber with a thin fluffy head, some lacing but no visible rising carbonation. On the nose, brilliant ripe citrus - orange, grapefruit and tangerine. In the mouth, a touch of caramel and honey add to the citrus flavours, very slight astringency, minimal sweetness with a short - crisp - mid-bitter finish. An almost perfect IPL.",
                            ImageURL = "https://birka.bg/wp-content/uploads/2019/04/bas.jpg",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 355,
                            Name = "Bash Maistora",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        },
                        new
                        {
                            Id = new Guid("9af21ad7-d997-4fdb-b61e-8a32b780ef8e"),
                            ABV = 5.8f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pours clear honey-gold with a fluffy, pure white head. Rather a nice pithy, citrusy pale ale, with some bread crust, semi-ripe citrus, nips of pine. Light bodied with fine to average carbonation. Well balanced finish. ",
                            ImageURL = "https://birka.bg/wp-content/uploads/2019/11/%D0%B8%D0%BB%D0%BB.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 0,
                            Name = "Faster Bastard IPA",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        },
                        new
                        {
                            Id = new Guid("d14758c8-3840-4b45-a861-bca2dca49de6"),
                            ABV = 5.5f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Lightly hazy straw, heavy lacing but not much head or rising carbonation. On the nose, soft floral hops with bread and honey. In the mouth, soft rich flavours similar to the aromas, smooth texture, mild bitterness into a clean finish. A really good beer-flavoured beer.",
                            ImageURL = "https://birka.bg/wp-content/uploads/2019/10/8.jpg",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 0,
                            Name = "1 Vreme",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        },
                        new
                        {
                            Id = new Guid("781a1380-ad56-4717-94de-89fbe6997213"),
                            ABV = 5.5f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smoked chilli porter brewed with Rhombus Craft Brewery",
                            ImageURL = "https://birka.bg/wp-content/uploads/2018/10/%D1%85%D0%BE.jpg",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 0,
                            Name = "Hot Takova",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        },
                        new
                        {
                            Id = new Guid("e2e4bfd0-95e8-4b19-8666-731594961eb1"),
                            ABV = 5.5f,
                            BreweryId = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A stout brewed with bulgarian chestnut.",
                            ImageURL = "https://birka.bg/wp-content/uploads/2018/11/da.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 0,
                            Name = "Dami Kanyat",
                            Price = 0.0,
                            StyleId = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7")
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Brewery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89e0215e-2726-489b-8d63-b851b997f622"),
                            CountryId = new Guid("eee1a9ab-c409-42c4-ae07-f622a959bb0b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "KamenitzaAD"
                        },
                        new
                        {
                            Id = new Guid("3d046341-8215-453d-8647-cc5a63d039fb"),
                            CountryId = new Guid("eee1a9ab-c409-42c4-ae07-f622a959bb0b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Beer Bastards - Papa Brewery - Burgas"
                        },
                        new
                        {
                            Id = new Guid("70dc3f24-6681-4ca0-9a67-9e3e78fa8b93"),
                            CountryId = new Guid("eee1a9ab-c409-42c4-ae07-f622a959bb0b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eee1a9ab-c409-42c4-ae07-f622a959bb0b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("f444594e-5626-4c1e-b285-571f33930010"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("e0932858-11cb-4a27-87f2-8756649b8c86"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("56e91350-598b-4f55-94d9-eefd329f1861"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("7c1703b1-3f2a-4979-a9f0-7a176960c470"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Unknown"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RatingGiven")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("BeerOverflow.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("bit");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03461e43-1ebb-4035-8fa4-e5acf5c923f1"),
                            BeerId = new Guid("133e0d92-cedc-40a7-b8fd-e5669611b3dc"),
                            Content = "This is exellent beer",
                            CreatedOn = new DateTime(2020, 10, 10, 14, 30, 26, 977, DateTimeKind.Local).AddTicks(7884),
                            IsDeleted = false,
                            IsFlagged = false,
                            Likes = 120
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Style", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The classic Pale Ale is generally a deep-golden to copper colored, hop-forward ale with a balanced malt profile. This style specifically represents all generic Pale Ales (sometime called International Pale Ale) which are marketed as such and which cannot be defined as a specific regional Pale Ale style such as the American Pale Ale. This also includes beers marketed as Extra Pale Ale (XPA), a non-defined style that usually sits between an American Pale Ale and an India Pale Ale, a hop forward beer and generally more intense than an APA but not as hop-forward as an IPA. Sometimes, the XPA also refers to a session-strength or simply paler Pale Ale.",
                            IsDeleted = false,
                            Name = "Pale Ale"
                        },
                        new
                        {
                            Id = new Guid("f32de916-9ea8-4f93-96d2-732d1b01fe8e"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Unknown"
                        },
                        new
                        {
                            Id = new Guid("96cc020a-753d-4483-9531-02b0a83b0a66"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Brut India Pale Ale (IPA) is a very pale to light golden, very dry, highly effervescent variant of American IPA, usually highly hopped with aromatic hops, but with far less actual bitterness. Enzymes are used in the mash and/or fermenter along with highly fermentable wort and often adjuncts like rice and corn to achieve close to total attenuation, resulting in an absent residual malt sweetness. Hopped in a similar fashion to New England IPA, but without sweetness. Pale like a West Coast IPA, but without high bitterness. Highly carbonated like a Belgian Golden Strong ale, but even drier, and without Belgian spice and phenol character.",
                            IsDeleted = false,
                            Name = "IPA - Brut"
                        },
                        new
                        {
                            Id = new Guid("bad58025-7855-482b-8f96-e74c4c122a9b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The English India Pale Ale (IPA) is a hoppy, moderately-strong, very well-attenuated pale golden to deep amber British ale with a dry finish and a hoppy aroma and flavor. Generally will have more finish hops and less fruitiness and/or caramel than British pale ales and bitter and has less hop intensity and a more pronounced malt flavor than typical American versions. The modern IPA style generally refers to American IPA and its derivatives but this does not imply that English IPA isn't a proper IPA. Originally, the attributes of IPA that were important to its arrival in good condition from England to India by ship were that it was very well-attenuated, and heavily hopped.",
                            IsDeleted = false,
                            Name = "IPA - English"
                        },
                        new
                        {
                            Id = new Guid("ae339a73-e8cb-47f3-b250-a3d25c4cdedb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Old Ale is an light amber to very dark reddish-brown colored English ale of moderate to fairly significant alcoholic strength, bigger than standard beers, though usually not as strong or rich as barleywine and often tilted towards a maltier balance. The predominant defining quality for this style is the impression of age, which can manifest itself in different ways (complexity, lactic, Brett, oxidation, leather, vinous qualities are some recurring examples). Roughly overlapping the British Strong Ale and the lower end of the English Barley Wine styles, but always having an aged quality. Barley Wines tend to develop more of an overall mature quality, while Old Ales can show more of the barrel qualities. Old Peculier are also considered as an Old Ale.",
                            IsDeleted = false,
                            Name = "Old Ale"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BeerOverflow.Models.Beer", b =>
                {
                    b.HasOne("BeerOverflow.Models.Brewery", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.Style", "Style")
                        .WithMany("Beers")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.Brewery", b =>
                {
                    b.HasOne("BeerOverflow.Models.Country", "Country")
                        .WithMany("Breweries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.Rating", b =>
                {
                    b.HasOne("BeerOverflow.Models.Beer", "Beer")
                        .WithMany("Ratings")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.Review", b =>
                {
                    b.HasOne("BeerOverflow.Models.Beer", "Beer")
                        .WithMany("Reviews")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.User", null)
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
