// <auto-generated />
using System;
using BeerOverflow.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeerOverflow.Database.Migrations
{
    [DbContext(typeof(BeerOverflowDbContext))]
    [Migration("20201021204849_SeedRatings")]
    partial class SeedRatings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeerOverflow.Models.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ABV")
                        .HasColumnType("real");

                    b.Property<Guid>("BreweryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBeerOfTheMonth")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnlisted")
                        .HasColumnType("bit");

                    b.Property<int>("Mililiters")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("StyleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.HasIndex("StyleId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("133e0d92-cedc-40a7-b8fd-e5669611b3dc"),
                            ABV = 4.4f,
                            BreweryId = new Guid("89e0215e-2726-489b-8d63-b851b997f622"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Light beer with an extract content of 10.2 ° P.",
                            ImageURL = "kamenitza.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 330,
                            Name = "Kamenitza",
                            Price = 1.6000000238418579,
                            StyleId = new Guid("f32de916-9ea8-4f93-96d2-732d1b01fe8e")
                        },
                        new
                        {
                            Id = new Guid("f13cdf0f-9f3c-4435-a107-e265e016b7d3"),
                            ABV = 3f,
                            BreweryId = new Guid("89e0215e-2726-489b-8d63-b851b997f622"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Light seasonal fruit beer with an extract content of 8.3 ° P.",
                            ImageURL = "kamenitza-fresh-grapefruit.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 330,
                            Name = "Kamenitza Lemon Fresh",
                            Price = 1.7999999523162842,
                            StyleId = new Guid("b06a5dbd-f993-4379-af3e-6339377503fc")
                        },
                        new
                        {
                            Id = new Guid("643db2ce-29f2-4e33-a35d-3a36b9392ba0"),
                            ABV = 6f,
                            BreweryId = new Guid("0d56076c-82cb-469d-80db-afb64c7516f7"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A high-quality lager beer, the main ingredients of which are barley malt, water, hops and yeast. It is characterized by light golden color, moderate carbonation, fresh taste, with a slight aroma of malt and hops. Available on the market in glass bottles of 0.5 liters, as well as in PET bottles of 1 and 2 liters.",
                            ImageURL = "zagorka.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 1000,
                            Name = "Zagorka",
                            Price = 1.8999999761581421,
                            StyleId = new Guid("f32de916-9ea8-4f93-96d2-732d1b01fe8e")
                        },
                        new
                        {
                            Id = new Guid("f0e83b17-1a70-4b1a-9d77-05822eb6ca44"),
                            ABV = 6.7f,
                            BreweryId = new Guid("59aeb9e3-a5e9-432e-bae7-b2f5b1e45fc0"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "This beer really is BASI KEFA! White IPA with added wheat and tons of aromatic hops. Intense aroma of citrus and tropical fruits, and the taste is memorable, you can feel grapefruit, tangerine, mango. medium sweet, medium bitter fruit finish. Extremely easy to drink despite the alcohol content - 6.7!",
                            ImageURL = "basi-kefa.png",
                            IsBeerOfTheMonth = true,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 330,
                            Name = "Basi Kefa",
                            Price = 4.9000000953674316,
                            StyleId = new Guid("e662a6bf-b3e4-4c18-8e77-efd31e587b2c")
                        },
                        new
                        {
                            Id = new Guid("1855d14b-ccb6-43b8-a7b3-3936b5010293"),
                            ABV = 5.2f,
                            BreweryId = new Guid("411a38dd-0600-4eac-b991-305f1031257c"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A Belgian pilsner of between 4.8 and 5.2 percent ABV which was first brewed by Brouwerij Artois (the Artois Brewery) in Leuven, Belgium, in 1926. Since 2008, a 4.8 percent ABV version has also been sold in Britain, Ireland, Canada and Australia. Stella Artois is now owned by Interbrew International B.V. which is a subsidiary of the world's largest brewer, Anheuser-Busch InBev SA/NV.",
                            ImageURL = "stella-artois.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 500,
                            Name = "Stella Artois",
                            Price = 2.9000000953674316,
                            StyleId = new Guid("1c7f6d85-2301-411b-a5c5-dae9fcf347a3")
                        },
                        new
                        {
                            Id = new Guid("629bff51-3e11-4996-ac98-365a8d8a7a66"),
                            ABV = 4.3f,
                            BreweryId = new Guid("411a38dd-0600-4eac-b991-305f1031257c"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Busch Beer is made with the finest ingredients, including a blend of premium hops, exceptional barley malt, fine grains and crisp water. This recipe delivers a refreshingly smooth taste & easy finish.",
                            ImageURL = "busch.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 550,
                            Name = "Busch",
                            Price = 4.0,
                            StyleId = new Guid("77f9496e-0475-4165-ac5e-ee57039f108c")
                        },
                        new
                        {
                            Id = new Guid("d71a9d9d-706f-412d-adce-30c6af6a6af1"),
                            ABV = 5f,
                            BreweryId = new Guid("411a38dd-0600-4eac-b991-305f1031257c"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Budweiser is brewed with only the finest two-row and six-row barley malt, hand-selected from regional growers all across America.",
                            ImageURL = "budweiser-light.png",
                            IsBeerOfTheMonth = true,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 550,
                            Name = "Budweiser Light",
                            Price = 4.9000000953674316,
                            StyleId = new Guid("77f9496e-0475-4165-ac5e-ee57039f108c")
                        },
                        new
                        {
                            Id = new Guid("3c40cffd-1cda-4b0b-bc8e-bd117407a98d"),
                            ABV = 8.5f,
                            BreweryId = new Guid("9e2c5791-92a4-4593-add9-6530391572f9"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Duvel is a natural beer with a subtle bitterness, a refined flavour and a distinctive hop character. The unique brewing process, which takes about 90 days, guarantees a pure character, delicate effervescence and a pleasant sweet taste of alcohol.",
                            ImageURL = "duvel.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 100,
                            Name = "Duvel",
                            Price = 3.0,
                            StyleId = new Guid("ec61fe34-c639-433d-acac-98f092392099")
                        },
                        new
                        {
                            Id = new Guid("c9d64fcf-9e82-46f5-90d4-00e7871bc93d"),
                            ABV = 4.5f,
                            BreweryId = new Guid("9e2c5791-92a4-4593-add9-6530391572f9"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ever since 2007 the brewers at Duvel have been busy innovating with a third hop variety to give Duvel a surprising twist and some extra bitterness. Each spring this results in the launch of a unique Tripel Hop, which complements the rest of the Duvel range.",
                            ImageURL = "duvel-tripel-hop.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 100,
                            Name = "Duvel Tripel Hop",
                            Price = 3.5,
                            StyleId = new Guid("b06a5dbd-f993-4379-af3e-6339377503fc")
                        },
                        new
                        {
                            Id = new Guid("8fc141ac-8514-4545-bf57-c1e1f4078fbe"),
                            ABV = 5f,
                            BreweryId = new Guid("2a281f97-d2d4-4cde-93d3-92f8aac15b9a"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A pale lager beer with 5% alcohol by volume produced by the Dutch brewing company Heineken International. Heineken beer is sold in a green bottle with a red star.",
                            ImageURL = "heineken.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 450,
                            Name = "Heineken",
                            Price = 2.0,
                            StyleId = new Guid("77f9496e-0475-4165-ac5e-ee57039f108c")
                        },
                        new
                        {
                            Id = new Guid("6210036f-3e9e-4e90-81d3-aaafd0251391"),
                            ABV = 4.2f,
                            BreweryId = new Guid("b35ef87f-d03a-4777-a900-3c5e2af3c4e9"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "4.2 to 5.6% in the United States. 5% in Canada, and most of Europe; 4.2 or 4.3% ABV in Ireland and some European countries, 4.1% in Germany, 4.8% in Namibia and South Africa, and 6% in Australia and Japan.",
                            ImageURL = "guinness.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 500,
                            Name = "Guinness Original",
                            Price = 3.0999999046325684,
                            StyleId = new Guid("ec61fe34-c639-433d-acac-98f092392099")
                        },
                        new
                        {
                            Id = new Guid("aac55056-ef0a-4ffc-8c98-bd686dd5ba86"),
                            ABV = 3.5f,
                            BreweryId = new Guid("f51b60cc-33fb-4ad2-afb5-6248c0a2b6ab"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "According to the Amstel website, Amstel beer is pure - filtered which creates a full-strength beer without the calories and carbohydrates.",
                            ImageURL = "amstel.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 660,
                            Name = "Amstel",
                            Price = 2.0999999046325684,
                            StyleId = new Guid("77f9496e-0475-4165-ac5e-ee57039f108c")
                        },
                        new
                        {
                            Id = new Guid("14af2a6c-5376-459e-91de-b6078c5435ac"),
                            ABV = 4.5f,
                            BreweryId = new Guid("8582b4e3-3e97-47f6-a1c9-358252ddaf43"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Corona Extra is a pale lager produced by Mexican brewery Cervecería Modelo and owned by Belgian company AB InBev. It is commonly served with a wedge of lime or lemon in the neck of the bottle to add tartness and flavour.",
                            ImageURL = "corona.png",
                            IsBeerOfTheMonth = true,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 330,
                            Name = "Corona",
                            Price = 3.0,
                            StyleId = new Guid("77f9496e-0475-4165-ac5e-ee57039f108c")
                        },
                        new
                        {
                            Id = new Guid("365ed501-0156-4d62-aef4-1e04c68b8ed6"),
                            ABV = 4.7f,
                            BreweryId = new Guid("2b2ee52d-89e3-4229-a704-bbfb3724cc11"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "London Pride is the flagship beer of Fuller's Brewery. It is sold both cask-conditioned and bottled. London Pride has been brewed at the Griffin Brewery since 1958.",
                            ImageURL = "londons-pride.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 550,
                            Name = "London's Pride",
                            Price = 3.0,
                            StyleId = new Guid("ae339a73-e8cb-47f3-b250-a3d25c4cdedb")
                        },
                        new
                        {
                            Id = new Guid("0e2cff6f-b42a-414b-8e3c-81c157909a2a"),
                            ABV = 5f,
                            BreweryId = new Guid("2b2ee52d-89e3-4229-a704-bbfb3724cc11"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The UK’s best-selling organic beer, Fuller’s Organic Honey Dew buzzes with a zesty edge and subtle sweetness. Approved by the Soil Association, it’s a thing of natural beauty – pure, golden sunshine in a glass.",
                            ImageURL = "honey-dew.png",
                            IsBeerOfTheMonth = false,
                            IsDeleted = false,
                            IsUnlisted = false,
                            Mililiters = 350,
                            Name = "Honey Dew",
                            Price = 2.7000000476837158,
                            StyleId = new Guid("b06a5dbd-f993-4379-af3e-6339377503fc")
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Brewery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("89e0215e-2726-489b-8d63-b851b997f622"),
                            CountryId = new Guid("eee1a9ab-c409-42c4-ae07-f622a959bb0b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Kamenitza AD"
                        },
                        new
                        {
                            Id = new Guid("0d56076c-82cb-469d-80db-afb64c7516f7"),
                            CountryId = new Guid("eee1a9ab-c409-42c4-ae07-f622a959bb0b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Zagorka AD"
                        },
                        new
                        {
                            Id = new Guid("59aeb9e3-a5e9-432e-bae7-b2f5b1e45fc0"),
                            CountryId = new Guid("eee1a9ab-c409-42c4-ae07-f622a959bb0b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Beer Bastards"
                        },
                        new
                        {
                            Id = new Guid("411a38dd-0600-4eac-b991-305f1031257c"),
                            CountryId = new Guid("e1d02d9a-263f-4871-b685-bf63de6508c4"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Anheuser–Busch"
                        },
                        new
                        {
                            Id = new Guid("9e2c5791-92a4-4593-add9-6530391572f9"),
                            CountryId = new Guid("e1d02d9a-263f-4871-b685-bf63de6508c4"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Duvel Moortgat"
                        },
                        new
                        {
                            Id = new Guid("2a281f97-d2d4-4cde-93d3-92f8aac15b9a"),
                            CountryId = new Guid("ec10c1a9-eafe-4ddc-8474-cb5fec82d186"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Heineken International"
                        },
                        new
                        {
                            Id = new Guid("f51b60cc-33fb-4ad2-afb5-6248c0a2b6ab"),
                            CountryId = new Guid("ec10c1a9-eafe-4ddc-8474-cb5fec82d186"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Amstel Brouwerij"
                        },
                        new
                        {
                            Id = new Guid("b35ef87f-d03a-4777-a900-3c5e2af3c4e9"),
                            CountryId = new Guid("d60e1413-fac0-45a5-a020-c1b7e5221a67"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Diageo"
                        },
                        new
                        {
                            Id = new Guid("8582b4e3-3e97-47f6-a1c9-358252ddaf43"),
                            CountryId = new Guid("0305d3f1-56ad-4ada-a854-30640b17120a"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Grupo Modelo"
                        },
                        new
                        {
                            Id = new Guid("2b2ee52d-89e3-4229-a704-bbfb3724cc11"),
                            CountryId = new Guid("71c1e52c-2f50-4ef6-99c8-451483d3df09"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Fuller's Brewery"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eee1a9ab-c409-42c4-ae07-f622a959bb0b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISO = "BG",
                            IsDeleted = false,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("e1d02d9a-263f-4871-b685-bf63de6508c4"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISO = "BE",
                            IsDeleted = false,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("ec10c1a9-eafe-4ddc-8474-cb5fec82d186"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISO = "NL",
                            IsDeleted = false,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("d60e1413-fac0-45a5-a020-c1b7e5221a67"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISO = "IE",
                            IsDeleted = false,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("0305d3f1-56ad-4ada-a854-30640b17120a"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISO = "MX",
                            IsDeleted = false,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("71c1e52c-2f50-4ef6-99c8-451483d3df09"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISO = "UK",
                            IsDeleted = false,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("f444594e-5626-4c1e-b285-571f33930022"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISO = "RS",
                            IsDeleted = false,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("e0932858-11cb-4a27-87f2-8756649b8c88"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISO = "DE",
                            IsDeleted = false,
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.DrankList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.ToTable("DrankList");
                });

            modelBuilder.Entity("BeerOverflow.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RatingGiven")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8361b282-628c-4a5f-85c0-7ff31b62f8ce"),
                            BeerId = new Guid("643db2ce-29f2-4e33-a35d-3a36b9392ba0"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 3,
                            UserId = new Guid("3be6b2ff-021d-4da5-8639-31973b594cc5")
                        },
                        new
                        {
                            Id = new Guid("c5f9dde1-b7c4-4e82-8a25-56e4bd80f529"),
                            BeerId = new Guid("643db2ce-29f2-4e33-a35d-3a36b9392ba0"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 1,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("20d56571-b75b-4786-8ed0-8ea0f0d52b30"),
                            BeerId = new Guid("6210036f-3e9e-4e90-81d3-aaafd0251391"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 5,
                            UserId = new Guid("3be6b2ff-021d-4da5-8639-31973b594cc5")
                        },
                        new
                        {
                            Id = new Guid("288283ac-3bc8-478e-9dbf-15f02a26b6c9"),
                            BeerId = new Guid("8fc141ac-8514-4545-bf57-c1e1f4078fbe"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 4,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("e0abf438-1977-44d9-b2c6-67dc12d589e7"),
                            BeerId = new Guid("14af2a6c-5376-459e-91de-b6078c5435ac"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 2,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("11d42d94-5526-4a32-bb14-622d5ee84fa5"),
                            BeerId = new Guid("14af2a6c-5376-459e-91de-b6078c5435ac"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 5,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("70ee7f0f-0861-4677-859b-dc2ac1c3dac7"),
                            BeerId = new Guid("c9d64fcf-9e82-46f5-90d4-00e7871bc93d"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 2,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("5bab4988-5026-4938-8e50-0049fe53dfb6"),
                            BeerId = new Guid("c9d64fcf-9e82-46f5-90d4-00e7871bc93d"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 3,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("d5579fa3-7e49-42f6-a162-9a763c05bed4"),
                            BeerId = new Guid("aac55056-ef0a-4ffc-8c98-bd686dd5ba86"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 3,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("15212aaf-11a3-422a-b1ff-39c4d73ef88a"),
                            BeerId = new Guid("aac55056-ef0a-4ffc-8c98-bd686dd5ba86"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 3,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("f72598cc-512e-4557-887b-2fdccbc4c431"),
                            BeerId = new Guid("0e2cff6f-b42a-414b-8e3c-81c157909a2a"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 4,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("3a3b81d6-e757-4119-ab15-68ccc5c75913"),
                            BeerId = new Guid("0e2cff6f-b42a-414b-8e3c-81c157909a2a"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 5,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("d46d615a-dd22-44c6-9199-9e7693a92297"),
                            BeerId = new Guid("365ed501-0156-4d62-aef4-1e04c68b8ed6"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 2,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("5606f196-8843-4142-bdb6-23ad0cf666c8"),
                            BeerId = new Guid("365ed501-0156-4d62-aef4-1e04c68b8ed6"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 5,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("04fca02d-6179-4fb2-b4c9-1414cc5b622a"),
                            BeerId = new Guid("c9d64fcf-9e82-46f5-90d4-00e7871bc93d"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 1,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("39263ac3-348c-41be-a85c-137ddca7b556"),
                            BeerId = new Guid("c9d64fcf-9e82-46f5-90d4-00e7871bc93d"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 3,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("19540f39-26ee-4329-ba79-2d3fb040ab40"),
                            BeerId = new Guid("d71a9d9d-706f-412d-adce-30c6af6a6af1"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 4,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("d341d0ef-2f1f-472c-beef-06cbdd084c2c"),
                            BeerId = new Guid("d71a9d9d-706f-412d-adce-30c6af6a6af1"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            RatingGiven = 3,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("bit");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03461e43-1ebb-4035-8fa4-e5acf5c923f1"),
                            BeerId = new Guid("643db2ce-29f2-4e33-a35d-3a36b9392ba0"),
                            Content = "This is exellent beer!",
                            CreatedOn = new DateTime(2020, 10, 21, 23, 48, 48, 585, DateTimeKind.Local).AddTicks(2097),
                            IsDeleted = false,
                            IsFlagged = false,
                            Likes = 120,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("8fc141ac-8514-4545-bf57-c1e1f4078fbe"),
                            BeerId = new Guid("1855d14b-ccb6-43b8-a7b3-3936b5010293"),
                            Content = "I didn't really like it. Poor colour, bad taste.",
                            CreatedOn = new DateTime(2020, 10, 21, 23, 48, 48, 589, DateTimeKind.Local).AddTicks(7072),
                            IsDeleted = false,
                            IsFlagged = false,
                            Likes = 8,
                            ModifiedOn = new DateTime(2020, 10, 22, 23, 48, 48, 589, DateTimeKind.Local).AddTicks(7161),
                            UserId = new Guid("3be6b2ff-021d-4da5-8639-31973b594cc5")
                        },
                        new
                        {
                            Id = new Guid("bc9fa1aa-d58a-4f37-a81d-7a7ca81f27bb"),
                            BeerId = new Guid("f13cdf0f-9f3c-4435-a107-e265e016b7d3"),
                            Content = "It's okay I guess. Very fruity aroma. Light sour, strong sweet taste. Fruity.",
                            CreatedOn = new DateTime(2020, 10, 21, 23, 48, 48, 589, DateTimeKind.Local).AddTicks(7407),
                            IsDeleted = false,
                            IsFlagged = false,
                            Likes = 22,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("766d9e58-68da-479c-ab97-dc9d1de06bbc"),
                            BeerId = new Guid("643db2ce-29f2-4e33-a35d-3a36b9392ba0"),
                            Content = "Absolutely amazing!. One of the best Bulgarian beers.",
                            CreatedOn = new DateTime(2020, 10, 21, 23, 48, 48, 589, DateTimeKind.Local).AddTicks(7430),
                            IsDeleted = false,
                            IsFlagged = false,
                            Likes = 0,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("ea4c9558-3832-403c-b70e-7ad0ef13b0a9"),
                            BeerId = new Guid("8fc141ac-8514-4545-bf57-c1e1f4078fbe"),
                            Content = "50/50. Sometimes win, sometimes lun.",
                            CreatedOn = new DateTime(2020, 10, 21, 23, 48, 48, 589, DateTimeKind.Local).AddTicks(7447),
                            IsDeleted = false,
                            IsFlagged = false,
                            Likes = 14,
                            UserId = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270")
                        },
                        new
                        {
                            Id = new Guid("ad9f46e6-5bcf-44f7-89cc-0325be7c20de"),
                            BeerId = new Guid("14af2a6c-5376-459e-91de-b6078c5435ac"),
                            Content = "Very unexpected. Be careful around it!",
                            CreatedOn = new DateTime(2020, 10, 21, 23, 48, 48, 589, DateTimeKind.Local).AddTicks(7470),
                            IsDeleted = false,
                            IsFlagged = false,
                            Likes = 19,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        },
                        new
                        {
                            Id = new Guid("f404463b-440d-4a45-ae57-6a00df49212e"),
                            BeerId = new Guid("14af2a6c-5376-459e-91de-b6078c5435ac"),
                            Content = "I am scared of that beer.",
                            CreatedOn = new DateTime(2020, 10, 21, 23, 48, 48, 589, DateTimeKind.Local).AddTicks(7484),
                            IsDeleted = false,
                            IsFlagged = false,
                            Likes = 200,
                            UserId = new Guid("3753d26b-5a35-491f-ae82-5238d243b619")
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("BeerOverflow.Models.Style", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f32de916-9ea8-4f93-96d2-732d1b01fe8e"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lager is a type of beer conditioned at low temperature. Lagers can be pale, amber, or dark.",
                            IsDeleted = false,
                            Name = "Lager"
                        },
                        new
                        {
                            Id = new Guid("b06a5dbd-f993-4379-af3e-6339377503fc"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fruit beer is beer made with fruit added as an adjunct or flavouring. Lambics, beers originating in the valley of the Zenne (in an around Brussels) Belgium, though copied by brewers in other parts of the world, may be refermented with cherries to make kriek, or fermented with raspberries to make framboise.",
                            IsDeleted = false,
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = new Guid("1c7f6d85-2301-411b-a5c5-dae9fcf347a3"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pilsner (also pilsener or simply pils) is a type of pale lager. It takes its name from the Czech city of Pilsen, where it was first produced in 1842 by Bavarian brewer Josef Groll. The world's first pale lager, the original Pilsner Urquell, is still produced there today.",
                            IsDeleted = false,
                            Name = "Pilsner"
                        },
                        new
                        {
                            Id = new Guid("77f9496e-0475-4165-ac5e-ee57039f108c"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pale lager is a very pale-to-golden-colored lager beer with a well-attenuated body and a varying degree of noble hop bitterness.",
                            IsDeleted = false,
                            Name = "Pale Lager"
                        },
                        new
                        {
                            Id = new Guid("ec61fe34-c639-433d-acac-98f092392099"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stout is a dark, top-fermented beer with a number of variations, including dry stout, oatmeal stout, milk stout, and imperial stout. The first known use of the word stout for beer was in a document dated 1677 found in the Egerton Manuscripts, the sense being that a \"stout beer\" was a strong beer, not a dark beer.",
                            IsDeleted = false,
                            Name = "Stout"
                        },
                        new
                        {
                            Id = new Guid("ae339a73-e8cb-47f3-b250-a3d25c4cdedb"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Old Ale is an light amber to very dark reddish-brown colored English ale of moderate to fairly significant alcoholic strength, bigger than standard beers, though usually not as strong or rich as barleywine and often tilted towards a maltier balance. The predominant defining quality for this style is the impression of age, which can manifest itself in different ways (complexity, lactic, Brett, oxidation, leather, vinous qualities are some recurring examples). Roughly overlapping the British Strong Ale and the lower end of the English Barley Wine styles, but always having an aged quality. Barley Wines tend to develop more of an overall mature quality, while Old Ales can show more of the barrel qualities. Old Peculier are also considered as an Old Ale.",
                            IsDeleted = false,
                            Name = "Old Ale"
                        },
                        new
                        {
                            Id = new Guid("e662a6bf-b3e4-4c18-8e77-efd31e587b2c"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "White IPAs are clear or hazy, golden-colored beers that are a hybrid of the hop-forward American India pale ale style and the traditional Belgian wit style.",
                            IsDeleted = false,
                            Name = "IPA - White"
                        },
                        new
                        {
                            Id = new Guid("49657e0d-b39c-48ed-92ea-839e0f33afd7"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The classic Pale Ale is generally a deep-golden to copper colored, hop-forward ale with a balanced malt profile. This style specifically represents all generic Pale Ales (sometime called International Pale Ale) which are marketed as such and which cannot be defined as a specific regional Pale Ale style such as the American Pale Ale. This also includes beers marketed as Extra Pale Ale (XPA), a non-defined style that usually sits between an American Pale Ale and an India Pale Ale, a hop forward beer and generally more intense than an APA but not as hop-forward as an IPA. Sometimes, the XPA also refers to a session-strength or simply paler Pale Ale.",
                            IsDeleted = false,
                            Name = "Pale Ale"
                        },
                        new
                        {
                            Id = new Guid("96cc020a-753d-4483-9531-02b0a83b0a66"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Brut India Pale Ale (IPA) is a very pale to light golden, very dry, highly effervescent variant of American IPA, usually highly hopped with aromatic hops, but with far less actual bitterness. Enzymes are used in the mash and/or fermenter along with highly fermentable wort and often adjuncts like rice and corn to achieve close to total attenuation, resulting in an absent residual malt sweetness. Hopped in a similar fashion to New England IPA, but without sweetness. Pale like a West Coast IPA, but without high bitterness. Highly carbonated like a Belgian Golden Strong ale, but even drier, and without Belgian spice and phenol character.",
                            IsDeleted = false,
                            Name = "IPA - Brut"
                        },
                        new
                        {
                            Id = new Guid("bad58025-7855-482b-8f96-e74c4c122a9b"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The English India Pale Ale (IPA) is a hoppy, moderately-strong, very well-attenuated pale golden to deep amber British ale with a dry finish and a hoppy aroma and flavor. Generally will have more finish hops and less fruitiness and/or caramel than British pale ales and bitter and has less hop intensity and a more pronounced malt flavor than typical American versions. The modern IPA style generally refers to American IPA and its derivatives but this does not imply that English IPA isn't a proper IPA. Originally, the attributes of IPA that were important to its arrival in good condition from England to India by ship were that it was very well-attenuated, and heavily hopped.",
                            IsDeleted = false,
                            Name = "IPA - English"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d6e3bae-451f-4c01-8b43-cecc2d404270"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "e0d087bd-f782-4785-8a9f-47ae35c174d9",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maggieemail@gmail.com",
                            EmailConfirmed = false,
                            IsBanned = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Maggie"
                        },
                        new
                        {
                            Id = new Guid("3be6b2ff-021d-4da5-8639-31973b594cc5"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "b74a7f98-4f0f-4ea0-abc7-031f7055e44b",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aliemail@gmail.com",
                            EmailConfirmed = false,
                            IsBanned = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Ali"
                        },
                        new
                        {
                            Id = new Guid("3753d26b-5a35-491f-ae82-5238d243b619"),
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "0358f039-9ea0-4dfb-a6e4-8de77ebbdea8",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "telerikemail@gmail.com",
                            EmailConfirmed = false,
                            IsBanned = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Telerik"
                        });
                });

            modelBuilder.Entity("BeerOverflow.Models.WishList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BeerId");

                    b.HasIndex("UserId");

                    b.ToTable("WishList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BeerOverflow.Models.Beer", b =>
                {
                    b.HasOne("BeerOverflow.Models.Brewery", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.Style", "Style")
                        .WithMany("Beers")
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.Brewery", b =>
                {
                    b.HasOne("BeerOverflow.Models.Country", "Country")
                        .WithMany("Breweries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.DrankList", b =>
                {
                    b.HasOne("BeerOverflow.Models.Beer", "Beer")
                        .WithMany("DrankList")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.User", "User")
                        .WithMany("DrankList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.Rating", b =>
                {
                    b.HasOne("BeerOverflow.Models.Beer", "Beer")
                        .WithMany("Ratings")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.Review", b =>
                {
                    b.HasOne("BeerOverflow.Models.Beer", "Beer")
                        .WithMany("Reviews")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BeerOverflow.Models.WishList", b =>
                {
                    b.HasOne("BeerOverflow.Models.Beer", "Beer")
                        .WithMany("Wishlist")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("BeerOverflow.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BeerOverflow.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BeerOverflow.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("BeerOverflow.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeerOverflow.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BeerOverflow.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
